# Generated by Django 4.0.6 on 2022-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='iframe',
            field=models.CharField(max_length=1000),
        ),
    ]
