# Generated by Django 4.0.6 on 2022-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_alter_topics_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
